name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Cambia esto a la rama que deseas usar para el despliegue (por ejemplo, `main` o `master`)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Configurar AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1  # Ajusta la región según tu entorno

    # Paso 2: Verificar el acceso a ECR
    - name: Verify AWS ECR Access
      run: aws ecr describe-repositories

    # Paso 3: Autenticarse en Docker para ECR
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 676206909059.dkr.ecr.eu-north-1.amazonaws.com

    # Paso 4: Crear imagen Docker y subir a ECR
    - name: Build and push Docker image
      run: |
        docker build -t image-crud .
        docker tag image-crud 676206909059.dkr.ecr.eu-west-1.amazonaws.com/image-crud
        docker push 676206909059.dkr.ecr.eu-west-1.amazonaws.com/image-crud

    # Paso 5: Desplegar en Elastic Beanstalk
    - name: Deploy to Elastic Beanstalk
      run: |
        eb init -p docker image-crud --region eu-north-1
        eb deploy Imagesgalery-env 
